# Generated by Django 4.2.9 on 2024-01-28 13:08

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to=backend.models.news_image_upload_location)),
            ],
        ),
    ]
