# Generated by Django 4.2.9 on 2024-02-07 23:43

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=backend.models.picture_upload_location)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.album')),
            ],
        ),
    ]
