# Generated by Django 4.2.13 on 2026-04-25 11:42

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.models.sponsor_logo_upload)),
                ('extra', models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.models.sponsor_extra_image_upload)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='backend.album'),
        ),
    ]
