# Generated by Django 4.2.13 on 2026-04-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_sponsor_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
