# Generated by Django 4.2.30 on 2026-05-19 17:48

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_sponsor_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to=backend.models.routes_image_upload)),
            ],
        ),
    ]
