# Generated by Django 4.2.30 on 2026-05-21 22:14

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_routeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'Image 1'), (2, 'Image 2'), (3, 'Image 3'), (4, 'Image 4'), (5, 'Image 5'), (6, 'Image 6'), (7, 'Image 7'), (8, 'Image 8')], unique=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.models.routes_walking_image_upload)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
