# Generated by Django 4.2.30 on 2026-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Image di5'), (2, 'Image wo5'), (3, 'Image do5'), (4, 'Image vr5'), (5, 'Image di10'), (6, 'Image wo10'), (7, 'Image do10'), (8, 'Image vr10')], unique=True),
        ),
    ]
